service imap-login {
  inet_listener imap {
    address = 127.0.0.1
    port = 143
  }
  inet_listener imaps {
    port = 0
  }
}

service submission-login {
  inet_listener submission {
    address = 127.0.0.1
    port = 587
  }
}
